name: test
runs-name: for events $ {{github.event_name}}

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: "Hello world1"
jobs:
  test:
    steps:
      - name: run the test
        run: echo "${{ inputs.name }}"